### ISSUE TITLE
Modificación de diseño de home del sitio

### ISSUE THREAD

**Issue by lu1s-cruz** [TheJorges/Artworks#2]
Mejorar el diseño de la vista de inicio del proyecto. Puede considerarse incluir un catálogo de colecciones de ejemplo para usuarios que no han iniciado sesión.

![Image](https://github.com/TheJorges/Artworks/assets/44510625/63359df0-cae8-41a5-9776-f2d83043f99b)

**Comment by JorgePintor** [comment]
Se modifico el diseño del home para ser responsivo, ajustándose de manera automática al tamaño de la ventana del navegador. También se modifico el diseño para que las pinturas ocupen su espacio apropiado y no se sobrepongan unas sobre otras.
